// ! Temporary, get these from backend later
export const CATEGORIES = [
    '🎤 Music',
    '🏫 Education',
    '🏈 Sports',
    '🏘️ Residence Life',
    '⛪️ Chapel',
    '👫 Social Activities',
    '🎨 Arts & Culture',
    '🧬 Science & Tech',
    '🗓️ Other',
    '🩺 Health & Fitness',
    '💼 Career & Business',
    '🎮 Gaming',
    '🎬 Film & Media',
    '🍔 Food & Drink',
];

export const EVENTS: CalvinEvent[] = [
    {
        name: 'Maroon & Gold Day',
        date: new Date('2022-04-02'),
        location: 'Calvin University',
        description: 'Gold',
        type: 'education',
    },
    {
        name: 'Cornhole Tournament',
        date: new Date('2022-04-02'),
        location: 'Calvin University',
        description: 'Gold',
        type: 'sports',
        price: 15,
    },
    {
        name: 'Maroon & Gold Day',
        date: new Date('2022-04-02'),
        location: 'Calvin University',
        description: 'Gold',
        type: 'education',
    },
    {
        name: 'Cornhole Tournament',
        date: new Date('2022-04-02'),
        location: 'Calvin University',
        description: 'Gold',
        type: 'sports',
    },
    {
        name: 'Maroon & Gold Day',
        date: new Date('2022-04-02'),
        location: 'Calvin University',
        description: 'Gold',
        type: 'education',
    },
    {
        name: 'Cornhole Tournament',
        date: new Date('2022-04-02'),
        location: 'Calvin University',
        description: 'Gold',
        type: 'sports',
    },
    {
        name: 'Maroon & Gold Day',
        date: new Date('2022-04-02'),
        location: 'Calvin University',
        description: 'Gold',
        type: 'education',
    },
    {
        name: 'Cornhole Tournament',
        date: new Date('2022-04-02'),
        location: 'Calvin University',
        description: 'Gold',
        type: 'sports',
    },
    {
        name: 'Maroon & Gold Day',
        date: new Date('2022-04-02'),
        location: 'Calvin University',
        description: 'Gold',
        type: 'education',
    },
    {
        name: 'Cornhole Tournament',
        date: new Date('2022-04-02'),
        location: 'Calvin University',
        description: 'Gold',
        type: 'sports',
    },
];
